- name: nginx
  become: yes
  hosts: all
  tasks:
    - name: intsalling httpd on centos
      package:
        name: "{{package_name}}"
        update_cache: true
        state: present 
      when: ansible_facts['os_family'] == "RedHat"
    - name : enable and start httpd
      ansible.builtin.systemd:
        name: "{{package_name}}"
        enabled: true
        state: started
      
        