- name: docker
  hosts: appserver
  become: yes
  tasks:
    - name: fail for unsupported operating systems
      ansible.builtin.fail:
        msg: "This palybook is written only for Ubuntu os"
      when: ansible_facts['distribution'] != "Ubuntu"
    - name : getting docker 
      ansible.builtin.get_url:
        url: "{{ docker_url }}"
        dest: /tmp/get-docker.sh
    - ansible.builtin.debug:
        msg: " docker installed on Ubuntu"
    - name: get docker script
      ansible.builtin.shell: "sh /tmp/get-docker.sh"
    - ansible.builtin.debug:
        msg: " got docker script "



