- name: installing php
  hosts: all
  become: yes
  vars:
    package: apache2
  tasks:
    - name: fail on when comes to other os
      ansible.builtin.fail:
        msg: "This playbook is designed only for Ubuntu os"
      when: ansible_facts['distribution'] != 'Ubuntu'
    - name: installing apache2
      ansible.builtin.apt:
        name: "{{ package }}"
        update_cache: yes
        state: present 
    - name: enable and start apache2
      ansible.builtin.service:
        name: "{{ package }}"
        state: started
    - name: intsall php packages 
      ansible.builtin.apt:
        name: "{{ php_packages }}"
        update_cache: yes
        state: present 
    - name: restart apache 
      ansible.builtin.service:
        name: "{{ package }}"
        state: restarted
    - name: copy php.info
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
    - name: restart apache 
      ansible.builtin.service:
        name: "{{ package }}"
        state: restarted

    
