- name: nopcommerce
  hosts: appserver
  become: yes
  tasks:
    - name: fail for unsupported operating systems
      ansible.builtin.fail:
        msg: " This playbook is designed only for the Ubuntu os"
      when: ansible_facts['distribution'] != 'Ubuntu'
    - name: installing nginx
      ansible.builtin.apt:
        name: "{{ package }}"
        update_cache: yes
        state: present 
    - ansible.builtin.debug:
        msg: "nginx is installed"
      notify:
        - start nginx
    - name: downloading nopCommerce
      ansible.builtin.get_url:
        url: "{{ nop_url }}"
        dest: "{{ home_dir }}"
    - ansible.builtin.debug:
        msg: "downloading nopCommerce"
    - ansible.builtin.stat:
        path: "{{ home_dir }}"
      register: nop_file
    - ansible.builtin.debug:
        msg: "download only if not exists"
      when: "not the nop_file.stat.exists"
    - ansible.builtin.debug:
        msg: " nopCommerce is downloaded to the {{ home_dir }}"      
  handlers:
    - name: start nginx
      ansible.builtin.systemd_service:
        name: nginx
        enabled: true
        state: started  