- name: nopcommerce
  hosts: appserver
  become: yes
  tasks:
    - name: fail for unsupported operating systems
      ansible.builtin.fail:
        msg: " This playbook is designed only for the Ubuntu os"
      when: ansible_facts['distribution'] != 'Ubuntu'
    - name: registering microsoftkey
      ansible.builtin.get_url:
        url: "{{ feed_url }}"
        dest: "{{ feed_dir }}"
    - ansible.builtin.debug:
        msg: " registering key"
    - ansible.builtin.stat:
        path: "{{ feed_dir }}"
      register: package_file
    - ansible.builtin.debug:
        msg: "implement only if not exists"
    - name: implementing package
      ansible.builtin.dpkg_selections:
        name: "{{ feed_package }}"
        selection: install 
    - ansible.builtin.debug:
        msg: "completed setting up packages"
      when: "not package_file.stat.exists"
    - name: installing nginx
      ansible.builtin.apt:
        name: "{{ package }}"
        update_cache: yes
        state: present 
    - ansible.builtin.debug:
        msg: "nginx is installed"
      notify:
        - start nginx
    - name: downloading nopCommerce
      ansible.builtin.get_url:
        url: "{{ nop_url }}"
        dest: "{{ home_dir }}"
    - ansible.builtin.debug:
        msg: "downloading nopCommerce"
      notify:
        - start nopCommerce
    - ansible.builtin.stat:
        path: "{{ home_dir }}"
      register: nop_file
    - ansible.builtin.debug:
        msg: "download only if not exists"
    - name: unzipping nopCommerce
      ansible.builtin.unarchive:
        src: "{{ nop_url }}"
        dest: "{{ home_dir}}"  
        remote_src: yes
      when: "not nop_file.stat.exists"
    - ansible.builtin.debug:
        msg: " nopCommerce is downloaded to the {{ home_dir }}" 
    - name: changing onwership
      ansible.builtin.file:
        path: "{{ home_dir}}"
        owner: "{{ user }}"
        group: "{{ group }}"
  handlers:
    - name: start nginx
      ansible.builtin.systemd_service:
        name: nginx
        enabled: true
        state: started  
    - name: restart nginx
      ansible.builtin.systemd_service:
        name: nginx
        enabled: true
        state: restarted  
    - name: start nopCommerce
      ansible.builtin.systemd_service:
        name: nopCommerce
        daemon_reload: yes
        enabled: yes
        state: started