---
- name: spc 
  hosts: jayserver
  become: yes
  tasks:
    - name: run on specified os
      ansible.builtin.fail:
        msg: " fail on unsupported os"
      when: ansible_facts['distribution']!= 'Ubuntu'
    - name: installing java
      ansible.builtin.apt:
        name: "{{ java }}"
        update_cache: yes
        state: present 
    - ansible.builtin.debug:
        msg: "installing java"
    - name: installing petclinic
      ansible.builtin.get_url:
        url: "{{ spc_url }}"
        dest: "{{ spc_dirr }}"
    - ansible.builtin.debug:
      msg: " installing pet clinic"
