---
- name: spc 
  hosts: jayserver
  become: yes
  tasks:
    - name: run on specified os
      ansible.builtin.fail:
        msg: " fail on unsupported os"
      when: ansible_facts['distribution']!= 'Ubuntu'
    - name: installing java
      ansible.builtin.apt:
        name: "{{ java }}"
        update_cache: yes
        state: present 
    - ansible.builtin.debug:
        msg: "installing java"
    - name: adding directory
      ansible.builtin.file:
        path: "{{ maven_dir }}"
        state: directory
    - name: building maven
      ansible.builtin.get_url:
        url: "{{ maven_url }}"
        dest: "{{ maven_dir }}"
    - ansible.builtin.debug:
        msg: "builded maven"
    - name: xtracting the maven
      ansible.builtin.unarchive:
        src: "{{ maven_url }}"
        dest: "{{ maven_dir }}"
        remote_src: yes
    

    
       
      
 