---
- name: spc 
  hosts: jayserver
  become: yes
  tasks:
    - name: run on specified os
      ansible.builtin.fail:
        msg: " fail on unsupported os"
      when: ansible_facts['distribution']!= 'Ubuntu'
    - name: installing java
      ansible.builtin.apt:
        name: "{{ java }}"
        update_cache: yes
        state: present 
    - ansible.builtin.debug:
        msg: "installing java"
    - name: adding dir 
      ansible.builtin.file:
        path: "{{ home_dir }}"
        state: directory
    - name: building maven
      ansible.builtin.get_url:
        url: "{{ maven_url }}"
        dest: "{{ home_dir }}"
    - ansible.builtin.debug:
        msg: "maven builded"
    - name: installing petclinic
      ansible.builtin.get_url:
        url: "{{ spc_url }}"
        dest: "{{ spc_dir }}"
      notify:
        restart spring-petclinic
    - ansible.builtin.debug:
        msg: "installing pet clinic"
  handlers:
    - name: restart spring-petclinic
      ansible.builtin.systemd_service:
        name: spring-petclinic
        enabled: true
        daemon_reload: yes
        state: restarted  